/**
 * ClearPath Knowledge Base
 * Full reference for all 35 scored VPPA/PPA terms.
 * Each entry: concept, whyMatters, scoring (per value with rationale),
 * watchFor (red flags), exampleLanguage (favorable vs unfavorable sample text)
 */

'use strict';

const KB = {

  // ─── DEAL ECONOMICS ────────────────────────────────────────────────────────

  strike: {
    id: 'strike',
    e2key: 'strike',
    tier: 'economics',
    weight: 4,
    title: 'Strike Price & Escalator',
    concept: `The strike price is the fixed $/MWh price used to settle the contract. In a VPPA, the buyer pays the strike price to the developer and receives the floating market price in return — so if market prices are below the strike, the buyer nets pays; if above, the buyer nets receives. Escalators (typically CPI-linked, 0–2%) determine how the strike drifts over the contract term.`,
    whyMatters: `The strike price is the single most financially significant term. It determines your long-run cost of offtake and your exposure to market price volatility. A strike set too high locks you into above-market payments for 15–20 years. A strike at or below market creates meaningful upside. Escalators compound: a 2% annual escalator on a $60 strike reaches $82/MWh by year 15.`,
    scoring: [
      { label: 'Buyer Favorable (BF zone)', score: '0–30', rationale: 'Strike is at or below the bottom of current market range for this ISO and technology. Buyer has meaningful upside if prices hold or rise. Low financial risk.' },
      { label: 'Market (Mkt zone)', score: '31–60', rationale: 'Strike is within the prevailing market range. Neither party is receiving unusual value. Fair deal at current market conditions.' },
      { label: 'Seller Favorable (SF zone)', score: '61–80', rationale: 'Strike is above market. Buyer is committing to above-market payments. Acceptable only if buyer has strategic reasons (additionality, location, specific developer relationship).' },
      { label: 'Reject (RF zone)', score: '81–100', rationale: 'Strike is materially above market. No credible financial justification for a corporate buyer. Renegotiate or walk away.' },
    ],
    watchFor: [
      'CPI escalators above 1.5% — compounding effect is severe over 20 years',
      'Floor/ceiling escalators that limit buyer upside but not seller protection',
      'No escalator disclosure — ask explicitly what the escalation mechanism is',
      'Strike priced on historical averages rather than forward curves',
    ],
    favorable: `"Strike Price of $44.50/MWh, subject to annual CPI escalation capped at 1.5% per year."`,
    unfavorable: `"Strike Price of $68.00/MWh, escalating at CPI + 0.5% per year, with a floor of 2.0% annual increase."`,
  },

  basis: {
    id: 'basis',
    e2key: 'basis',
    tier: 'economics',
    weight: 4,
    title: 'Basis Risk',
    concept: `Basis risk is the difference between the price at the project's delivery node (where generation physically occurs) and the hub or zonal price used for settlement. A solar project in West Texas may generate at a node where prices are $8/MWh lower than the ERCOT hub — that $8 gap is basis. In a VPPA, who bears this gap matters enormously to long-run economics.`,
    whyMatters: `Basis risk is one of the most underestimated risks in corporate PPAs. Nodal-to-hub spreads in ERCOT can exceed $15/MWh on average for congested projects, representing 30–40% of a project's revenue. If the buyer bears this risk, a project that looks favorable at $45/MWh hub price may net to $30/MWh in actual settlement. Always ask for 3-year historical nodal data before signing.`,
    scoring: [
      { label: 'Seller bears', score: '10', rationale: 'Developer takes on basis exposure. Project revenue is reduced when node prices lag hub, but buyer is fully insulated. Most buyer-favorable allocation.' },
      { label: 'Shared with collar', score: '35', rationale: 'Collar mechanism limits buyer exposure to a defined $/MWh band. Buyer has some risk but it is bounded and quantifiable.' },
      { label: 'Buyer bears', score: '65', rationale: 'Buyer absorbs all nodal price variability. Settlement is based on nodal price, not hub. High risk for congested nodes or projects in transmission-constrained regions.' },
      { label: 'Not specified', score: '75', rationale: 'Silence defaults to buyer bearing basis risk in most standard VPPA structures. A material gap in the term sheet.' },
    ],
    watchFor: [
      'Nodal settlement in ERCOT West or South zones — historically severe basis',
      'No historical nodal price data provided in the data room',
      'Collar bands wider than $5/MWh — effectively buyer bears basis',
      'Busbar transfer provisions buried in technical schedules',
    ],
    favorable: `"Settlement shall be based on the Hub price. Seller bears all nodal-to-hub basis risk. If the Project's node-to-hub spread exceeds $3/MWh in any month, Seller shall true up to Buyer within 30 days."`,
    unfavorable: `"Settlement shall be based on the ERCOT nodal price at the Project's delivery point. Buyer acknowledges and accepts all basis risk associated with nodal-to-hub price differentials."`,
  },

  negprice: {
    id: 'negprice',
    e2key: 'negprice',
    tier: 'economics',
    weight: 4,
    title: 'Negative Price Provisions',
    concept: `Negative electricity prices occur when supply exceeds demand — most commonly in ERCOT and CAISO during spring/fall low-load periods when solar and wind flood the grid. In a VPPA, if prices go negative and the project is still generating, the buyer owes the developer the strike price AND pays the negative price — effectively paying twice. Negative price provisions determine whether the project curtails, the buyer gets a floor, or the buyer absorbs all downside.`,
    whyMatters: `In ERCOT, negative price hours have increased from ~200/year in 2018 to over 1,000/year in 2023–24 as solar penetration has grown. For a 200 MW solar project with 25% capacity factor generating into -$20/MWh prices for 500 hours, that is $50M+ in cumulative negative settlement payments to the buyer over a 15-year contract. This term has gone from minor to deal-critical.`,
    scoring: [
      { label: 'Zero floor', score: '5', rationale: 'Settlement price floors at $0 — buyer never owes more than the strike price regardless of how negative the market goes. Maximum protection.' },
      { label: 'Seller curtails', score: '30', rationale: 'Developer must curtail generation during negative price periods (within defined parameters). Buyer gets practical protection through reduced generation, not a price floor.' },
      { label: 'Full passthrough', score: '70', rationale: 'Buyer absorbs negative prices fully. In high-penetration markets, this can be a material financial exposure. Requires careful quantitative modeling before accepting.' },
      { label: 'Not specified', score: '85', rationale: 'No provision found. Under standard VPPA mechanics, buyer bears full negative price exposure. Critical gap — must be addressed before execution.' },
    ],
    watchFor: [
      'No hourly cap on seller curtailment rights — unlimited curtailment destroys energy production',
      'Annual aggregate caps that reset — watch for gaming near reset dates',
      'Price floors set at -$10 or -$20 rather than $0 — partial protection only',
      'ERCOT and CAISO deals without negative price provisions — high-risk markets',
    ],
    favorable: `"During any Settlement Interval in which the Applicable Price is negative, the Applicable Price shall be deemed to be $0.00/MWh for purposes of calculating Settlement Amounts."`,
    unfavorable: `"Settlement Amounts shall be calculated using the actual Applicable Price for each Settlement Interval, including periods of negative pricing. Buyer acknowledges and accepts all negative price risk."`,
  },

  eterm: {
    id: 'eterm',
    e2key: 'eterm',
    tier: 'economics',
    weight: 4,
    title: 'Early Termination Payment',
    concept: `If a party terminates the agreement early — whether for breach, event of default, or a termination right — the non-defaulting party is owed a termination payment. How this payment is calculated determines whether early exit is practically feasible and how much credit risk exists. The three main approaches: mark-to-market (value of remaining contract vs current forward curves), fixed formula (predetermined schedule), or negotiated.`,
    whyMatters: `A corporate buyer's strategic position changes. M&A, sustainability policy shifts, financial stress — all can create a need to exit a 20-year contract. If termination payment = mark-to-market and electricity prices have risen since signing, the buyer owes the full economic value of the remaining deal to the seller. On a $200M notional VPPA, this can be $40–80M in early exit costs. The "defaulter pays" concept matters equally — if the developer defaults, does the buyer receive a fair payment?`,
    scoring: [
      { label: 'Mark-to-market + defaulter pays', score: '20', rationale: 'Both parties exposed to market value at termination. Buyer receives fair compensation if developer defaults. Market standard and balanced.' },
      { label: 'Fixed formula + defaulter pays', score: '10', rationale: 'Most buyer-favorable. Predictable exposure, no mark-to-market uncertainty. Buyer can model maximum downside on day one.' },
      { label: 'Negotiated + no defaulter pays', score: '55', rationale: 'Open-ended negotiation creates uncertainty. Lack of defaulter-pays means buyer may receive inadequate compensation for developer default.' },
      { label: 'Not specified + no defaulter pays', score: '75', rationale: 'No payment mechanics defined. Silence creates litigation risk and potentially no recourse for buyer on developer breach.' },
    ],
    watchFor: [
      'No cap on termination payment — open-ended mark-to-market over 15+ years',
      'Asymmetric provisions — buyer pays market value on exit, seller pays fixed (discounted) amount',
      'Termination triggers that exclude project underperformance',
      'Change of control triggers that require consent and create termination risk',
    ],
    favorable: `"Upon an Early Termination Date, the Defaulting Party shall pay the Non-Defaulting Party the Termination Payment, calculated as the present value of the remaining Contract Quantity at the Replacement Price less the Contract Price, subject to a cap of $[X]MM."`,
    unfavorable: `"In the event of termination for any reason, Buyer shall pay Seller a termination fee equal to the Net Present Value of all remaining Contract Payments, discounted at 6% per annum, with no offset for Buyer's benefit of lost contract payments."`,
  },

  floating: {
    id: 'floating',
    e2key: 'floating',
    tier: 'economics',
    weight: 4,
    title: 'Floating Settlement Point',
    concept: `In a VPPA, the buyer receives the floating market price and pays the strike. The "settlement point" defines which market price is used — hub (regional aggregate), zonal (sub-regional), or nodal (project-specific delivery point). "Adders included" means whether ancillary service revenues, capacity payments, or other products are bundled into the settlement.`,
    whyMatters: `Settlement point selection is one of the most commercially important but often overlooked terms. Hub settlement insulates the buyer from nodal congestion. Nodal settlement exposes the buyer to location-specific price discounts that can be severe and persistent. The difference between ERCOT hub and a congested West Texas node has averaged $8–12/MWh in recent years — a material impact on net settlement economics.`,
    scoring: [
      { label: 'Hub or Zonal — adders included', score: '5', rationale: 'Settled at liquid hub or zone with full ancillary revenue passthrough. Maximum buyer protection from basis, maximum revenue capture.' },
      { label: 'Hub or Zonal — adders excluded', score: '35', rationale: 'Settled at hub but developer retains ancillary revenues. Buyer does not benefit from capacity and ancillary upside. Acceptable but watch revenue stack.' },
      { label: 'Nodal — any', score: '55–75', rationale: 'Buyer bears nodal-to-hub basis. Acceptable only with strong basis provisions, historical nodal data review, and collar protection.' },
      { label: 'Not specified', score: '80', rationale: 'Critical gap. No agreed settlement point. In practice, nodal is default for most developers — buyer risks assuming basis exposure unknowingly.' },
    ],
    watchFor: [
      'Settlement point in transmission-constrained corridor without basis protection',
      'Node-to-hub spread not disclosed — always request 3-year historical data',
      '"Applicable Hub" defined broadly to include future ISOs or market redesigns',
      'Adders scope ambiguous — capacity market revenues in PJM can be material',
    ],
    favorable: `"Settlement shall be calculated using the Day-Ahead ERCOT Hub price (ERCOT_NORTH_HUB), inclusive of all ancillary service revenues attributable to the Contract Quantity."`,
    unfavorable: `"Settlement shall be calculated at the real-time nodal price at the Project's point of delivery. Buyer acknowledges the settlement point is subject to change based on ERCOT nodal pricing."`,
  },

  // ─── PROJECT RISK ──────────────────────────────────────────────────────────

  delay: {
    id: 'delay',
    e2key: 'delay',
    tier: 'risk',
    weight: 2,
    title: 'Delay & COD Damages',
    concept: `Construction delays are common in renewable energy. The "long-stop date" is the drop-dead date by which the project must achieve Commercial Operation — if it misses this date, the buyer may terminate. Delay liquidated damages (LDs) are pre-agreed payments from the developer to the buyer for each day/month the project is late. Together these define the buyer's practical protection against a project that never comes online.`,
    whyMatters: `A corporate buyer signs a VPPA to meet a renewable energy target — often tied to public commitments, board approvals, or regulatory obligations. A 2-year delay with no damages and no termination right means the buyer has committed capital, made public announcements, and received nothing. Delay LD caps are equally important: a $2M cap on a $200M project provides minimal incentive for the developer to perform.`,
    scoring: [
      { label: 'Long-stop + termination right', score: '10', rationale: 'Buyer has both a financial remedy (LDs) and an exit right if the project misses its long-stop. Maximum protection against developer underperformance.' },
      { label: 'Long-stop, no termination right', score: '35', rationale: 'Some protection but buyer is trapped if project significantly delays. LDs may be limited and capped.' },
      { label: 'No long-stop + termination right', score: '45', rationale: 'Buyer can exit but only after indefinite delay. No financial compensation for the wait.' },
      { label: 'No long-stop, no termination', score: '75', rationale: 'Buyer has no contractual protection against delay. Open-ended obligation with no exit. Unacceptable in most corporate procurement contexts.' },
    ],
    watchFor: [
      'LD caps below 15% of total contract value — insufficient incentive to perform',
      'Long-stop dates with unlimited extension rights for "force majeure" — watch for broad FM definition',
      'No milestone schedule attached — inability to monitor progress',
      'Target COD vs. guaranteed COD — make sure it is the latter',
    ],
    favorable: `"If the Project fails to achieve Commercial Operation by the Long-Stop Date, Buyer may terminate this Agreement upon 30 days' written notice. Developer shall pay delay liquidated damages of $[X]/day from the Target COD through the Long-Stop Date, capped at 15% of the aggregate Contract Value."`,
    unfavorable: `"The Target COD is [date], subject to extension for Force Majeure, permitting delays, interconnection queue delays, or any other circumstances beyond Developer's reasonable control. No termination right is granted to Buyer for failure to achieve COD."`,
  },

  curtailment: {
    id: 'curtailment',
    e2key: 'curtailment',
    tier: 'risk',
    weight: 2,
    title: 'Economic Curtailment',
    concept: `Economic curtailment occurs when the grid operator or developer reduces or stops generation for economic reasons — typically because real-time prices are so low that generation is uneconomic. In a VPPA, the question is: if the project curtails economically, does the buyer receive "deemed generation" (the MWh they would have received at contract price) or only the MWh actually generated?`,
    whyMatters: `Economic curtailment is increasingly common as renewable penetration grows. A project in ERCOT may curtail 5–15% of potential generation per year for economic reasons. If the developer can curtail without deemed generation, the buyer's renewable energy volume falls short of targets and the financial hedge is less effective. Conversely, if buyer bears curtailment, the buyer's energy procurement position can be significantly under-hedged.`,
    scoring: [
      { label: 'Seller bears (deemed generation)', score: '10', rationale: 'Developer provides deemed generation for economically curtailed MWh. Buyer receives contract volumes regardless. Maximum protection.' },
      { label: 'Shared', score: '40', rationale: 'Some curtailment risk shared — typically above a threshold, buyer bears the excess. Risk is bounded but real.' },
      { label: 'Buyer bears', score: '65', rationale: 'Buyer receives only actual generation. Volume shortfalls directly reduce renewable energy coverage and hedge effectiveness.' },
      { label: 'Not specified', score: '75', rationale: 'No provision found. Default is typically buyer bears risk. Material gap — must clarify before execution.' },
    ],
    watchFor: [
      'No cap on developer curtailment rights — unlimited economic curtailment is effectively a call option to not perform',
      'Deemed generation formula that uses P50 rather than actual metered output',
      'Curtailment rights exercisable at developer discretion rather than ISO instruction',
    ],
    favorable: `"In the event of Economic Curtailment of the Project, Seller shall calculate and pay Buyer Deemed Generation for all curtailed MWh, based on the Project's metered output from comparable non-curtailed periods."`,
    unfavorable: `"Seller shall have the right to curtail generation at any time for economic reasons without liability. Settlement shall be based solely on actual metered output."`,
  },

  nonecocurtail: {
    id: 'nonecocurtail',
    e2key: 'nonecocurtail',
    tier: 'risk',
    weight: 2,
    title: 'Non-Economic Curtailment',
    concept: `Non-economic curtailment (also called "instructed curtailment") occurs when the grid operator orders the project to reduce output for reliability or congestion reasons — not because prices are low, but because the grid physically can't absorb more power. The ISO issues a dispatch instruction and the project must comply. Transmission constraints, local reliability events, and system emergencies all trigger this.`,
    whyMatters: `Non-economic curtailment is growing as solar and wind buildout outpaces transmission investment. In some ERCOT zones, non-economic curtailment regularly exceeds 5–10% of potential generation annually. Unlike economic curtailment (which at least correlates with low settlement prices), non-economic curtailment creates pure volume shortfall with no offsetting price benefit to the buyer.`,
    scoring: [
      { label: 'Seller bears (deemed generation)', score: '15', rationale: 'Developer provides deemed generation for grid-instructed curtailment. Buyer fully protected from volume shortfall.' },
      { label: 'Shared', score: '35', rationale: 'Risk shared above a threshold (typically 50–100 hours/year buyer bears, seller bears excess). Bounded risk.' },
      { label: 'Buyer bears', score: '60', rationale: 'Buyer absorbs all instructed curtailment. Volume shortfall risk in congested areas can be material.' },
      { label: 'Not specified', score: '70', rationale: 'Gap in documentation. Most developers will argue buyer bears instructed curtailment under standard VPPA mechanics.' },
    ],
    watchFor: [
      'Broad definition of "grid instruction" that captures economic dispatch signals',
      'No distinction between seller-caused outages and ISO-instructed curtailment',
      'Deemed generation calculated on P90 rather than P50 — significantly reduces compensation',
    ],
    favorable: `"In the event of any Instructed Curtailment ordered by the relevant ISO, Seller shall provide Deemed Generation to Buyer equal to the estimated metered output that would have been generated absent such curtailment, using the 30-day rolling P50 generation profile."`,
    unfavorable: `"Seller shall not be liable for any reduction in output resulting from ISO dispatch instructions, transmission constraints, or system reliability events. No Deemed Generation shall be owed for Instructed Curtailment."`,
  },

  basiscurtail: {
    id: 'basiscurtail',
    e2key: 'basiscurtail',
    tier: 'risk',
    weight: 2,
    title: 'Basis Curtailment',
    concept: `Basis curtailment is a hybrid: the project curtails economically because the nodal price has gone deeply negative, but the real cause is transmission congestion (a grid constraint problem, not just oversupply). Some contracts treat this as economic curtailment (developer may curtail, no deemed generation), others treat it as a special case warranting buyer protection since the root cause is a grid infrastructure issue rather than resource oversupply.`,
    whyMatters: `In ERCOT West, basis curtailment during high-solar periods has increased dramatically. A project may see nodal prices of -$30/MWh when hub is +$20/MWh — a $50 basis gap. The project rationally curtails. If buyer bears this, they receive no generation AND no settlement payments during periods they most needed the hedge (high daytime demand periods). Understanding this distinction is critical for ERCOT solar deals.`,
    scoring: [
      { label: 'Seller bears (deemed generation)', score: '10', rationale: 'Developer treats basis curtailment like instructed curtailment. Buyer receives deemed generation. Most protective.' },
      { label: 'Shared', score: '40', rationale: 'Partial protection. Developer provides deemed generation above a threshold basis spread (e.g., node is >$10/MWh below hub).' },
      { label: 'Buyer bears', score: '70', rationale: 'Buyer absorbs all basis curtailment. Particularly risky for ERCOT solar in West/South zones.' },
      { label: 'Not specified', score: '78', rationale: 'Critical gap for ERCOT solar. Very likely to default to buyer-bears under standard VPPA mechanics.' },
    ],
    watchFor: [
      'No definition of basis curtailment separate from economic curtailment',
      'ERCOT solar deals in constrained zones (West, South) — elevated basis curtailment probability',
      'Threshold triggers for deemed generation set too high (e.g., nodal must be <-$50) — ineffective protection',
    ],
    favorable: `"'Basis Curtailment' means any curtailment occurring when the nodal price at the Delivery Point is more than $[X]/MWh below the Settlement Hub price. Seller shall provide Deemed Generation for all Basis Curtailment hours."`,
    unfavorable: `"All curtailment decisions by Seller are at Seller's sole discretion. Deemed generation provisions do not apply to any curtailment made for economic reasons, including basis-related curtailment."`,
  },

  fm: {
    id: 'fm',
    e2key: 'fm',
    tier: 'risk',
    weight: 2,
    title: 'Force Majeure',
    concept: `Force majeure excuses performance obligations when specified events beyond a party's control occur — hurricanes, acts of war, pandemic, grid failure. The key commercial questions: how broadly is FM defined, does FM excuse the payment obligation (or only performance), and how long can FM persist before either party can terminate?`,
    whyMatters: `Broad FM definitions are effectively "get out of jail free" cards for the developer. A developer who has a poorly performing project can invoke a broadly drafted FM clause to excuse delivery shortfalls. The distinction between FM excusing performance (delivery of MWh) vs. FM excusing payment (settlement obligation) is critical — no FM clause should excuse a party from paying money already owed.`,
    scoring: [
      { label: 'Narrow + does not excuse payment', score: '10', rationale: 'FM limited to true catastrophic events (war, terrorism, natural disaster). Payment obligations survive FM. Most buyer-favorable.' },
      { label: 'Standard + does not excuse payment', score: '25', rationale: 'Industry-standard FM definition. Payments still due even during FM period. Acceptable.' },
      { label: 'Broad + excuses payment', score: '75', rationale: 'Wide FM definition includes routine operational issues. Payment excused. Developer has significant optionality to underperform without liability.' },
      { label: 'Not specified', score: '55', rationale: 'No FM clause is unusual and creates ambiguity. Courts will imply FM-like protections anyway. Request explicit drafting.' },
    ],
    watchFor: [
      'FM definitions that include "curtailment by grid operator" — this is an operational event, not force majeure',
      'No FM duration cap — developer could claim FM indefinitely',
      'FM excusing payment obligations — this is non-standard and seller-favorable',
      '"Change in law" buried in FM definition — should be a separate term with its own treatment',
    ],
    favorable: `"'Force Majeure Event' means any act of God, act of war, terrorism, or government action that (a) is not reasonably foreseeable, (b) is beyond the affected Party's reasonable control, and (c) cannot be overcome with reasonable efforts. Force Majeure shall not excuse any payment obligation."`,
    unfavorable: `"'Force Majeure Event' means any event beyond a Party's reasonable control, including without limitation adverse weather, curtailment by the grid operator, changes in market conditions, supply chain disruptions, or any other event that materially and adversely affects performance. Force Majeure shall excuse all payment obligations during the pendency of such event."`,
  },

  changeinlaw: {
    id: 'changeinlaw',
    e2key: 'changeinlaw',
    tier: 'risk',
    weight: 2,
    title: 'Change in Law',
    concept: `Change in Law provisions determine what happens when a new law, regulation, tax, or grid rule materially changes the economics of the contract after execution. The three allocations: buyer bears the change (most common for certain tax changes), seller bears it (developer absorbs policy risk), or shared through automatic price adjustment or renegotiation.`,
    whyMatters: `In a 15–20 year contract, regulatory change is nearly certain. FERC market redesigns, state renewable portfolio standard changes, interconnection rule modifications, and carbon pricing all affect VPPA economics. Who bears this risk determines whether the contract is durable through policy shifts. Corporate buyers should push to share regulatory risk rather than absorb it unilaterally.`,
    scoring: [
      { label: 'Seller bears — automatic adjustment', score: '10', rationale: 'Developer adjusts pricing automatically to reflect regulatory changes. Buyer is fully protected from adverse law changes. Maximum buyer protection.' },
      { label: 'Shared — negotiated adjustment', score: '30', rationale: 'Parties negotiate impact of law change and adjust contract terms. Balanced allocation. Industry standard for well-negotiated deals.' },
      { label: 'Buyer bears — automatic adjustment', score: '65', rationale: 'Buyer absorbs regulatory changes through automatic price increases. Developer is insulated. Buyer has significant open-ended exposure.' },
      { label: 'Buyer bears — no adjustment', score: '75', rationale: 'Buyer bears all regulatory risk with no price mechanism. Most adverse outcome — buyer absorbs cost increases with no contract relief.' },
    ],
    watchFor: [
      'Change in law that includes tax law changes but excludes FERC market rule changes (or vice versa)',
      'No materiality threshold — any regulatory change triggers renegotiation (creates disruption risk)',
      'Change in law definition so broad it captures normal market evolution',
      'One-sided: buyer bears adverse changes, but seller retains benefit of favorable changes',
    ],
    favorable: `"If a Change in Law materially and adversely affects either Party's costs or obligations under this Agreement, the Parties shall negotiate in good faith to equitably adjust the Contract Price or other terms to reflect the impact of such Change in Law."`,
    unfavorable: `"Buyer shall bear all costs and obligations arising from any Change in Law affecting the generation, delivery, settlement, or taxation of energy under this Agreement, including any increases in grid fees, transmission charges, or compliance costs."`,
  },

  ia: {
    id: 'ia',
    e2key: 'ia',
    tier: 'risk',
    weight: 2,
    title: 'Interconnection Agreement',
    concept: `The Interconnection Agreement (IA) is the contract between the project and the grid operator (ISO or utility) that gives the project the right to connect to the transmission system and deliver power. The IA process can take 3–6+ years and involves significant costs (network upgrade contributions). Where a project is in this process directly determines how "real" the project is and how likely it is to achieve COD on schedule.`,
    whyMatters: `Interconnection is the single biggest project development risk after permitting. A project with only a feasibility study complete has a 50%+ historical attrition rate — it may never reach COD, or may reach it 3–4 years late. A buyer signing with a project that hasn't cleared interconnection is essentially signing with a development-stage opportunity, not a committed project.`,
    scoring: [
      { label: 'Fully executed IA', score: '5', rationale: 'Project has a signed interconnection agreement. The hardest regulatory hurdle is cleared. Delivery risk is primarily construction, not regulatory.' },
      { label: 'Facilities study complete', score: '20', rationale: 'Project has cleared the expensive study phase and understands its network upgrade costs. High probability of IA execution.' },
      { label: 'System impact study complete', score: '35', rationale: 'Project has cleared an early study milestone. Network upgrade costs are indicative but not final. Moderate development risk.' },
      { label: 'Feasibility study only', score: '55', rationale: 'Early stage. Project has a queue position but limited certainty on costs or timeline. Significant execution risk.' },
      { label: 'Not filed', score: '85', rationale: 'No interconnection queue position. Project is purely conceptual. Extremely high execution risk. Not appropriate for a binding VPPA.' },
    ],
    watchFor: [
      'Network upgrade contribution not disclosed — can be $50–200M+ and may make project uneconomic',
      'IA milestone not tied to COD longstop dates — project could fail IA without buyer right to terminate',
      'Multiple projects sharing a point of interconnection — queue jumping risk',
      'ERCOT transition to COGE process — different timelines than legacy SGIA',
    ],
    favorable: `"As of the Effective Date, Seller has executed an Interconnection Agreement with [ISO] for the interconnection of the Project at [substation]. Network Upgrade Costs are fixed at $[X]M per the executed IA."`,
    unfavorable: `"Seller has submitted a request for a Feasibility Study with [ISO]. Seller shall use commercially reasonable efforts to advance the interconnection process. No termination right is granted to Buyer if Seller fails to obtain executed IA."`,
  },

  cp: {
    id: 'cp',
    e2key: 'cp',
    tier: 'risk',
    weight: 2,
    title: 'Conditions Precedent',
    concept: `Conditions Precedent (CPs) are contractual conditions that must be satisfied before the agreement becomes binding or before certain obligations begin. Seller CPs are conditions the developer must satisfy — each one is effectively an option for the seller to walk away if the condition isn't met. Buyer CPs are conditions the buyer must satisfy. From a buyer's perspective, seller CPs are the primary risk: they represent the developer's exit options before committing.`,
    whyMatters: `A VPPA with 4 seller CPs (financing, permitting, interconnection, and board approval) is not really a committed contract — it is a letter of intent with a purchase option for the developer. Each CP is a potential exit. If the developer raises equity in a declining market, fails to obtain a permit, or misses an interconnection deadline, they can simply not fulfill their CP and walk away — leaving the buyer with nothing after months of negotiation and board approval.`,
    scoring: [
      { label: '0 seller CPs', score: '10', rationale: 'Seller is fully committed from execution. No exit options. Most favorable allocation for buyer.' },
      { label: '1 seller CP', score: '30', rationale: 'One exit door for developer. Acceptable if the CP is narrow and time-limited (e.g., regulatory approval within 60 days).' },
      { label: '2 seller CPs', score: '50', rationale: 'Two exit options. Moderate risk. Depends heavily on how the CPs are defined and time-bounded.' },
      { label: '3+ seller CPs', score: '65–90', rationale: 'Developer has significant optionality before committing. Contract is more of a pre-agreement than a firm deal. Renegotiate or seek termination payment if CPs are not satisfied within defined periods.' },
    ],
    watchFor: [
      'Open-ended CP satisfaction deadlines — developer can delay indefinitely',
      'CP conditions defined in developer\'s sole discretion (e.g., "financing satisfactory to Seller")',
      'Financing CP with no termination payment to buyer if CP not met',
      'Buyer has no termination right if seller CPs are not satisfied within a defined window',
    ],
    favorable: `"This Agreement is not subject to any conditions precedent by Seller. This Agreement shall be fully binding upon execution by both Parties."`,
    unfavorable: `"This Agreement is conditioned upon: (a) Seller obtaining construction financing satisfactory to Seller in its sole discretion; (b) Seller obtaining all required environmental permits; (c) Seller executing an Interconnection Agreement; and (d) Seller's board approval of the Project. Seller may terminate this Agreement if any Seller CP is not satisfied within 18 months."`,
  },

  permit: {
    id: 'permit',
    e2key: 'permit',
    tier: 'risk',
    weight: 2,
    title: 'Permitting Status',
    concept: `Renewable energy projects require numerous permits — environmental impact assessments, land use permits, air quality permits, FAA determinations, and more. Permitting status at contract execution determines how much regulatory uncertainty remains. A fully permitted project is shovel-ready; a not-yet-started permitting process can take 2–5 additional years and may ultimately be denied.`,
    whyMatters: `Permitting failure is the second most common cause of renewable project attrition after interconnection. Buyer commitments made against unpermitted projects carry meaningful risk that the project never reaches COD. A buyer who publicly commits to a 150 MW solar project and then sees it fail permitting three years later faces reputational damage and procurement shortfall.`,
    scoring: [
      { label: 'All permits obtained', score: '5', rationale: 'Project is fully permitted. Regulatory risk is de minimis. No permitting-related delay or failure risk.' },
      { label: 'Major permits obtained', score: '18', rationale: 'Primary regulatory hurdles cleared. Remaining permits are routine and unlikely to fail or cause significant delay.' },
      { label: 'In progress', score: '40', rationale: 'Permitting is active. Timeline and outcome uncertain. 12–36 month exposure to regulatory process.' },
      { label: 'Not started', score: '70', rationale: 'No permitting begun. Project is very early stage. Significant regulatory risk. Inappropriate for a committed long-term VPPA.' },
    ],
    watchFor: [
      'NEPA review not yet initiated — can add 2–4 years',
      'Projects in counties with history of renewable opposition',
      'Offshore wind permitting (separate BOEM process) not yet begun',
      'No permit milestone schedule or termination right for permitting failure',
    ],
    favorable: `"As of the Effective Date, Seller has obtained all material permits required for construction and operation of the Project, including [list]. Seller represents that no permit is subject to material challenge or appeal."`,
    unfavorable: `"Seller is in the process of applying for all required permits. Seller shall use commercially reasonable efforts to obtain all permits required for Project construction and operation, but makes no representation as to the timing or likelihood of approval."`,
  },

  cod: {
    id: 'cod',
    e2key: 'cod',
    tier: 'risk',
    weight: 2,
    title: 'COD Definition',
    concept: `Commercial Operation Date (COD) is the date the project is deemed to be commercially operational and the contract term officially begins. The definition matters: a tight, objective definition (a specific MW threshold interconnected and tested) ensures the buyer knows exactly what they're paying for. A loose "substantial completion" definition allows the developer to declare COD with a fraction of contracted capacity online.`,
    whyMatters: `If COD is defined loosely, a developer could bring 30% of a contracted project online, declare COD, start the contract term, and then spend the next 18 months completing the remaining capacity — all while the buyer's contract clock is running. The buyer's renewable energy accounting starts on COD, so a prematurely declared COD means years of under-delivery relative to expectations.`,
    scoring: [
      { label: 'Tight, objective definition', score: '8', rationale: '100% of contracted capacity interconnected, tested, and delivering. No ambiguity. Contract clock starts only when fully operational.' },
      { label: 'Moderate definition', score: '30', rationale: 'High threshold (e.g., 90%+ of contracted capacity) with clear test criteria. Limited gaming risk.' },
      { label: 'Loose / substantial completion', score: '58', rationale: '"Substantially complete" language with no defined capacity threshold. Developer has discretion to declare COD early. Material risk of under-delivery.' },
      { label: 'Not specified', score: '70', rationale: 'No COD definition. Parties will dispute when contract obligations commence. Significant litigation risk.' },
    ],
    watchFor: [
      '"Substantially complete" without a defined MW threshold',
      'COD definition that includes "initial commercial operation" of any portion of the project',
      'No independent verification or testing protocol for COD determination',
      'COD not tied to availability of transmission service (IA must be active)',
    ],
    favorable: `"'Commercial Operation Date' means the date on which 100% of the Nameplate Capacity has been synchronized to the grid, all interconnection upgrades are complete, and Seller has delivered to Buyer a certification from a qualified independent engineer confirming Project readiness."`,
    unfavorable: `"'Commercial Operation Date' means the date on which the Project achieves initial commercial operation of any portion of the Project, as determined by Seller in its reasonable discretion."`,
  },

  availmech: {
    id: 'availmech',
    e2key: 'availmech',
    tier: 'risk',
    weight: 2,
    title: 'Availability Mechanism',
    concept: `The availability mechanism defines how the contract handles periods when the project is available to generate but fails to achieve a guaranteed availability level. Remedies can be: deemed generation (buyer receives credit as if the project ran), liquidated damages (cash payment per MWh of shortfall), or nothing. This is the O&M performance backstop — distinct from the availability guarantee (which sets the threshold).`,
    whyMatters: `Solar and wind projects have O&M issues. Inverter failures, tracker problems, and curtailment can reduce actual availability below contracted levels. Without a remedy mechanism, the buyer simply receives less energy. With deemed generation, the buyer receives contract-equivalent value regardless of actual output. This term is the operational performance backstop for the entire deal.`,
    scoring: [
      { label: 'Deemed generation', score: '5', rationale: 'Buyer receives full contract value regardless of availability shortfall. Maximum protection. Effectively insures against O&M risk.' },
      { label: 'Liquidated damages', score: '15', rationale: 'Cash remedy for shortfall. Less complete than deemed generation but quantifiable and bankable.' },
      { label: 'No remedy / availability guarantee present', score: '15–55', rationale: 'Guarantee exists but no defined remedy for breach. Buyer must pursue general damages — less certain and more costly to enforce.' },
      { label: 'Not specified', score: '55', rationale: 'No availability mechanism. Buyer has no structural protection against O&M underperformance.' },
    ],
    watchFor: [
      'Deemed generation calculated on P90 rather than actual capacity — significantly reduced compensation',
      'LD caps that make remedy economically irrelevant (e.g., $50K/year cap on a 200 MW project)',
      'No independent measurement and verification protocol',
      'Availability calculated on energy-weighted basis vs. time-based — can be gamed',
    ],
    favorable: `"In any Contract Year in which the Project's Availability falls below the Guaranteed Availability, Seller shall provide Deemed Generation to Buyer equal to the energy the Project would have generated at its P50 capacity factor during the shortfall period."`,
    unfavorable: `"Seller shall use commercially reasonable efforts to maintain Project availability. No financial remedy is available to Buyer for availability shortfalls. Buyer's sole recourse is to seek general damages through dispute resolution."`,
  },

  availguaranteed: {
    id: 'availguaranteed',
    e2key: 'availguaranteed',
    tier: 'risk',
    weight: 2,
    title: 'Availability Guarantee',
    concept: `The availability guarantee sets the performance threshold — the minimum percentage of time (or energy-weighted equivalent) the project must be available to generate. P50, P75, and P90 refer to the probability basis: P90 means the project is expected to generate at or above the guaranteed level 90% of the time. A P90 guarantee is a low bar (very conservative); a P50 guarantee is the median expectation.`,
    whyMatters: `The P-value basis determines how often the guarantee is actually triggered. A P90 availability guarantee on a solar project is unlikely to be breached — by definition, the project should exceed P90 90% of the time. Contrast with a P50 guarantee: the project is expected to breach it half the time statistically. The guarantee level relative to the project's actual performance range determines the real value of the backstop.`,
    scoring: [
      { label: 'P50 basis — guaranty present', score: '10', rationale: 'Guarantee set at median performance. Will be triggered if project underperforms in any given year. Meaningful backstop.' },
      { label: 'P75 basis — guaranty present', score: '45', rationale: 'Conservative guarantee. Will only be triggered in years with meaningfully below-average performance.' },
      { label: 'P90 basis — guaranty present', score: '65', rationale: 'Very conservative guarantee. The project must perform very poorly before the guarantee triggers. Limited practical value.' },
      { label: 'No guaranty', score: '82', rationale: 'No performance backstop. Buyer has no contractual protection against sustained underperformance.' },
    ],
    watchFor: [
      'P90 guarantee with no remedy — the double protection gap (low threshold, no remedy)',
      'Energy-weighted vs. time-based measurement — can be structurally different',
      'No independent verification of P-value calculations',
      'Guarantee based on developer model, not independent resource assessment',
    ],
    favorable: `"Seller guarantees that the Project shall achieve an Availability of not less than [X]% on a P50 basis in each Contract Year, as measured by an independent engineer using SCADA data."`,
    unfavorable: `"Seller estimates the Project will achieve availability of approximately [X]% based on current resource assessments. No binding guarantee of availability is provided."`,
  },

  marketdisrupt: {
    id: 'marketdisrupt',
    e2key: 'marketdisrupt',
    tier: 'risk',
    weight: 2,
    title: 'Market Disruption',
    concept: `A market disruption event occurs when the relevant price index (hub price, nodal price) ceases to be published, is suspended, or is materially manipulated — rendering normal settlement impossible. The contract must specify a fallback mechanism: suspend settlement, use a historical average, use the most recent published price, or settle at strike (effectively no market payment). This is a low-probability but high-impact scenario.`,
    whyMatters: `Market manipulation events (ERCOT Winter Storm Uri in 2021, CAISO price caps) have demonstrated that settlement mechanisms can fail. A VPPA with no market disruption clause reverts to whatever the market operator does — which may mean months of price caps, retroactive adjustments, or suspended settlement. Defined fallbacks provide contractual certainty during extraordinary market events.`,
    scoring: [
      { label: 'Suspend settlement', score: '5', rationale: 'No settlement owed during disruption. Both parties wait. Clear, fair, and avoids adverse selection.' },
      { label: 'Fallback average price', score: '15', rationale: 'Use historical average price during disruption. Reasonable proxy. Industry standard.' },
      { label: 'Settle at last published price', score: '30', rationale: 'Use most recent pre-disruption price. Can be gamed near disruption events but generally reasonable.' },
      { label: 'Settle normally', score: '65', rationale: 'Party must find replacement price or estimate — introduces significant dispute risk during already-chaotic market conditions.' },
      { label: 'Not specified', score: '80', rationale: 'No fallback. Settlement uncertainty during market disruption. Contract silent on a material risk scenario.' },
    ],
    watchFor: [
      'No definition of what constitutes a "market disruption event"',
      'Fallback that allows one party to elect settlement method — creates adverse selection',
      'Duration limit on disruption provisions — what happens if disruption lasts more than 30 days?',
    ],
    favorable: `"'Market Disruption Event' means any day on which the Applicable Price is not published or is subject to retroactive revision by the relevant market operator. Upon a Market Disruption Event, settlement shall be suspended and recalculated using the 90-day rolling average Applicable Price once the disruption has resolved."`,
    unfavorable: `"Settlement shall be based on the Applicable Price as published by the relevant market operator. If the Applicable Price is not published, the Parties shall negotiate in good faith to determine an appropriate substitute price."`,
  },

  // ─── LEGAL & ADMIN ─────────────────────────────────────────────────────────

  interval: {
    id: 'interval',
    e2key: 'interval',
    tier: 'admin',
    weight: 1,
    title: 'Settlement Interval',
    concept: `The settlement interval defines how frequently energy generation and pricing are measured for settlement purposes. ISO-native (5-minute in most ISOs) captures real-time price volatility. Hourly aggregates 12 five-minute intervals. Monthly netting aggregates an entire month — in which case negative price hours are masked by positive price hours. Annual is the most aggregated and most buyer-adverse.`,
    whyMatters: `Settlement interval interacts directly with negative price exposure. A monthly settlement interval effectively creates a zero-floor on negative prices (negative hours are offset by positive hours in the same month). But it also means the buyer doesn't benefit from extremely high-price periods proportionally. For buyers in high-volatility markets (ERCOT, CAISO), hourly or ISO-native settlement provides the most accurate hedge.`,
    scoring: [
      { label: 'ISO-native (5-minute)', score: '5', rationale: 'Most granular. Settlement tracks actual market prices period by period. Best hedge accuracy but highest negative price exposure.' },
      { label: 'Hourly', score: '30', rationale: 'Industry standard. Balances granularity with administrative practicality. Widely used in corporate VPPA market.' },
      { label: 'Monthly', score: '60', rationale: 'Aggregated. Masks intra-month price volatility. Creates natural negative price offset but reduces hedge precision.' },
      { label: 'Annual', score: '75', rationale: 'Highly aggregated. Settlement is annual net. Minimal hedge value against short-term price spikes or negative periods.' },
    ],
    watchFor: [
      'Monthly or annual settlement in high-volatility markets — poor hedge effectiveness',
      'Settlement interval not aligned with buyer\'s energy procurement reporting period',
      'Mix of real-time and day-ahead prices in same settlement calculation',
    ],
    favorable: `"Settlement shall be calculated on an hourly basis using the Day-Ahead Locational Marginal Price published by [ISO] for the Settlement Point."`,
    unfavorable: `"Settlement shall be calculated on an annual basis using the average of all hourly LMPs published by [ISO] during each Contract Year."`,
  },

  invoice: {
    id: 'invoice',
    e2key: 'invoice',
    tier: 'admin',
    weight: 1,
    title: 'Invoicing & Payment Terms',
    concept: `Invoicing terms define how often settlement is billed (monthly, quarterly, annual), how long the paying party has to pay (payment terms in days), and what happens in disputes (pay-then-dispute vs. withhold-disputed-amounts). Netting provisions allow offsetting amounts owed in both directions before cash settlement. These terms affect working capital and counterparty credit exposure.`,
    whyMatters: `Payment terms define your working capital exposure. Monthly invoicing with 30-day terms is standard and manageable. Quarterly with 60-day terms means the buyer could owe 5 months of settlements before the first invoice is paid — significant cash flow exposure for a large VPPA. True-up mechanisms determine whether annual reconciliation creates big catch-up payments.`,
    scoring: [
      { label: 'Monthly frequency', score: '25', rationale: 'Frequent invoicing limits maximum outstanding settlement amounts. Preferred by treasury teams.' },
      { label: 'Quarterly frequency', score: '40', rationale: 'Moderate. Three months of settlement can accumulate before invoicing. Manageable for most corporates.' },
      { label: 'Annual frequency', score: '60', rationale: 'Full year of settlement before invoicing. Significant working capital exposure for active VPPAs.' },
    ],
    watchFor: [
      'Payment terms exceeding 45 days — counterparty credit exposure',
      'No netting provision — buyer pays gross even when offsetting amounts are owed by seller',
      'Annual true-up without monthly statements — no visibility into accrued position',
      'Late payment rate below market — no incentive for prompt payment',
    ],
    favorable: `"Seller shall issue invoices monthly within 5 Business Days following the end of each calendar month. Buyer shall pay all undisputed amounts within 30 days of invoice receipt. Netting shall apply to all amounts owed in both directions."`,
    unfavorable: `"Seller shall issue invoices quarterly. Buyer shall pay all invoiced amounts within 60 days. Disputed amounts must be paid in full prior to initiating dispute resolution."`,
  },

  scheduling: {
    id: 'scheduling',
    e2key: 'scheduling',
    tier: 'admin',
    weight: 1,
    title: 'Scheduling Control',
    concept: `Scheduling provisions determine who controls how the project's generation is scheduled in the day-ahead and real-time markets. ISO dispatch means the ISO automatically dispatches the project as a market resource. Seller-schedules means the developer controls dispatch and submits day-ahead bids. Buyer-approval means the buyer must approve the developer's dispatch schedule — providing visibility but adding administrative burden.`,
    whyMatters: `Scheduling control affects the quality of the energy hedge. If the developer schedules the project in a way that concentrates generation in low-price hours, the buyer's settlement receipts are reduced. ISO dispatch is generally market-optimal. Developer-controlled scheduling without oversight creates potential misalignment between generation timing and buyer's load profile.`,
    scoring: [
      { label: 'ISO dispatch', score: '15', rationale: 'Market-determined dispatch. Optimal price signal. No party gaming. Standard for most utility-scale renewable projects.' },
      { label: 'Buyer approval required', score: '10', rationale: 'Buyer has visibility and input into scheduling. Can align generation with load profile. Adds administrative overhead.' },
      { label: 'Seller schedules', score: '35', rationale: 'Developer controls dispatch. Potential misalignment with buyer interests. Ensure scheduling obligations are aligned with maximum revenue.' },
    ],
    watchFor: [
      'Developer scheduling discretion without obligation to maximize revenue',
      'No dispatch data sharing with buyer — no visibility into scheduling decisions',
      'Seller using generation for real-time market optimization at expense of day-ahead settlement',
    ],
    favorable: `"The Project shall be dispatched pursuant to ISO automatic generation control. Seller shall not override ISO dispatch instructions except for safety or equipment protection purposes. Seller shall provide Buyer with real-time SCADA access."`,
    unfavorable: `"Seller shall have sole discretion to schedule and dispatch the Project's generation, subject only to ISO operating requirements. Seller shall have no obligation to consult with or obtain approval from Buyer for any scheduling decision."`,
  },

  sellerpa: {
    id: 'sellerpa',
    e2key: 'sellerpa',
    tier: 'admin',
    weight: 1,
    title: 'Seller Performance Assurance',
    concept: `Seller performance assurance (PA) is the credit support the developer provides to ensure they can fulfill financial obligations under the contract — particularly the termination payment obligation if they breach or default. Forms include parent guaranty (from the developer's parent company), letters of credit (LOC from a bank), cash collateral, or nothing (SPV-only). Pre-COD guarantee covers obligations during construction; post-COD covers operational obligations.`,
    whyMatters: `A VPPA counterparty that is a project SPV with no parent support is effectively uncreditworthy. If the developer goes bankrupt or breaches pre-COD, the buyer's only recourse is against a shell company with no assets. An IG (investment grade) parent guaranty from a creditworthy developer is the gold standard — the buyer has a real counterparty to pursue. Credit support sizing and duration are equally important.`,
    scoring: [
      { label: 'IG sponsor guaranty + pre-COD guarantee', score: '5', rationale: 'Investment-grade parent provides full guaranty covering pre-COD obligations. Maximum credit protection.' },
      { label: 'Sponsor guaranty — no pre-COD', score: '28', rationale: 'Parent guaranty for operational period only. Pre-COD obligations uncovered. Gap during highest-risk project phase.' },
      { label: 'Letter of credit', score: '18–35', rationale: 'Bank LC provides direct cash support. Creditworthy but typically sized at cap amount, not full obligations.' },
      { label: 'SPV only — no PA', score: '55–78', rationale: 'No credit support. Buyer is exposed to a shell company. Recourse is contractual only — limited practical value.' },
    ],
    watchFor: [
      'SPV-only counterparty with no parent guaranty — assess parent\'s actual creditworthiness',
      'LC sized at termination payment cap only — may not cover all obligations',
      'PA expiring post-COD — operational period uncovered',
      'Developer parent is also an SPV or thinly capitalized holdco',
    ],
    favorable: `"Seller shall cause [Investment Grade Parent Company] to execute and deliver the Parent Guaranty substantially in the form attached hereto, covering all of Seller's obligations under this Agreement, including pre-COD obligations, with a face amount of not less than $[X]MM."`,
    unfavorable: `"Seller's obligations under this Agreement are solely those of [Project SPV LLC]. Buyer acknowledges that Seller has no obligation to provide any parent guaranty, letter of credit, or other credit support."`,
  },

  buyerpa: {
    id: 'buyerpa',
    e2key: 'buyerpa',
    tier: 'admin',
    weight: 1,
    title: 'Buyer Performance Assurance',
    concept: `Buyer PA is the credit support the corporate buyer provides to the developer to backstop its payment obligations. For investment-grade buyers, this is often unsecured (the developer trusts the buyer's credit). Non-IG buyers may need to post a letter of credit or cash collateral. The type and amount of buyer PA affects the buyer's available credit lines and administrative burden.`,
    whyMatters: `For IG-rated buyers, this term is largely administrative — the developer accepts the buyer's credit and PA requirements are minimal. For non-IG or unrated entities, PA requirements can be material: a $10M LOC requirement ties up bank credit capacity and has direct cost (typically 50–150bps/year). Mark-to-market PA requirements (where the amount floats with market value) can require additional posting during periods of high market prices.`,
    scoring: [
      { label: 'IG buyer — unsecured', score: '5', rationale: 'Developer accepts buyer credit on unsecured basis. No LOC, no cash. Most efficient for investment-grade corporates.' },
      { label: 'IG buyer — parent guaranty', score: '15', rationale: 'Minor additional documentation. Acceptable. Slightly more onerous than unsecured but not materially burdensome.' },
      { label: 'Non-IG — LOC + MTM', score: '8', rationale: 'For non-IG buyers: LOC plus mark-to-market posting. More onerous but appropriate given credit profile.' },
      { label: 'Non-IG — unsecured', score: '55', rationale: 'Developer accepting non-IG buyer unsecured — developer is taking meaningful credit risk. May reflect weak deal economics or aggressive developer.' },
    ],
    watchFor: [
      'MTM posting thresholds below $5M — frequent posting events during volatile markets',
      'PA required within 5 days of threshold breach — operational difficulty for treasury',
      'No release mechanism for PA as deal approaches end of term',
      'PA calculated on gross exposure, not net — ignores buyer\'s offsetting settlement receipts',
    ],
    favorable: `"Buyer shall provide performance assurance in the form of an unsecured obligation or parent guaranty. No letter of credit or cash collateral shall be required unless Buyer's credit rating falls below BBB-/Baa3."`,
    unfavorable: `"Buyer shall maintain a Letter of Credit in the amount of $[X]MM at all times during the Term, subject to increase if the Mark-to-Market exposure exceeds $[Y]MM. Buyer shall increase the Letter of Credit within 3 Business Days of any trigger event."`,
  },

  assign: {
    id: 'assign',
    e2key: 'assign',
    tier: 'admin',
    weight: 1,
    title: 'Assignment Rights',
    concept: `Assignment provisions determine whether and how either party can transfer its rights and obligations under the contract to a third party. Buyer assignment is common in M&A (parent assigns to subsidiary, or acquirer inherits target's contracts). Seller assignment happens when a developer sells the project to a new owner (very common — most renewable projects are sold post-COD). The key question: does assignment require consent, and what conditions apply?`,
    whyMatters: `In practice, corporate buyers are almost always sold or merged at some point during a 20-year VPPA. Assignment provisions determine whether the contract survives a change of control and how the buyer's obligations transfer. For sellers, project sales to institutional owners (pension funds, infrastructure investors) are routine — the buyer needs creditworthiness protections to ensure the new project owner can meet obligations.`,
    scoring: [
      { label: 'Narrow FM scope — obligations continue', score: '5', rationale: 'Assignment allowed under narrow conditions; obligations remain with assignee. Clean transfer mechanism. Balanced.' },
      { label: 'Narrow FM scope — obligations excused', score: '25', rationale: 'Assignment under narrow conditions excuses continuing obligations. Higher risk if used to escape underperforming contract.' },
      { label: 'Broad / subjective — obligations excused', score: '65', rationale: 'Developer can assign broadly; assignee may not inherit all obligations. Creates potential for contract avoidance through assignment.' },
    ],
    watchFor: [
      'Seller assignment without creditworthiness requirements for assignee — developer sells to uncreditworthy entity',
      'Change of control trigger not included — acquirer may inherit without buyer consent',
      'No assignment fee or consent right for buyer on seller assignment',
      'Broad assignment rights that could fragment contract across multiple entities',
    ],
    favorable: `"Neither Party may assign this Agreement without the prior written consent of the other Party (not to be unreasonably withheld), except that Seller may assign to a creditworthy successor owner of the Project, provided such successor executes an assumption agreement and meets the credit requirements herein."`,
    unfavorable: `"Seller may assign this Agreement without Buyer consent in connection with any financing, refinancing, or sale of the Project. Buyer may not assign this Agreement without Seller's prior written consent, which may be withheld in Seller's sole discretion."`,
  },

  eod: {
    id: 'eod',
    e2key: 'eod',
    tier: 'admin',
    weight: 1,
    title: 'Events of Default',
    concept: `Events of Default (EODs) define the specific circumstances that constitute a breach serious enough to trigger termination and/or termination payment rights. Common EODs: payment failure, insolvency, material breach, failure to maintain PA, change of control, loss of permits. Cross-default provisions trigger an EOD if a party defaults on other obligations (unrelated debt, other contracts).`,
    whyMatters: `EOD definitions determine how protected you are when a counterparty fails. Too-narrow EODs mean a fundamentally failing developer (late, underperforming, financially distressed) can stay on contract without triggering buyer's exit rights. Cross-default provisions provide early warning — if the developer defaults on project finance debt, that triggers an EOD giving the buyer an exit before the project fails.`,
    scoring: [
      { label: 'Cross-default + objective cure test', score: '5', rationale: 'Broad early-warning system with clear, objective cure rights. Buyer gets notice of counterparty distress and clear path to terminate.' },
      { label: 'Cross-default + subjective cure', score: '18', rationale: 'Cross-default present but cure determination is qualitative. Some ambiguity in enforcement.' },
      { label: 'No cross-default + objective cure', score: '30', rationale: 'Limited early-warning but at least termination mechanics are clear when EOD is triggered.' },
      { label: 'No cross-default + no cure right', score: '65', rationale: 'Narrow EOD definition, no early-warning, no cure right. Buyer has limited recourse if counterparty deteriorates.' },
    ],
    watchFor: [
      'EODs tied to seller\'s "material breach" without objective definition — hard to trigger',
      'No cure period provisions — potential disputes on whether breach has been cured',
      'Change of control EOD only at buyer\'s option — may not protect against developer\'s distress',
      'Insolvency EOD that only triggers on bankruptcy filing — should include insolvent events earlier',
    ],
    favorable: `"Events of Default include: (a) failure to make any payment when due, continuing for 3 Business Days; (b) cross-default on Project finance debt or any material contract; (c) insolvency or filing for bankruptcy protection; (d) loss of any material permit; (e) failure to maintain required Performance Assurance."`,
    unfavorable: `"Events of Default are limited to material breach of this Agreement that is not cured within 60 days of written notice. No cross-default provisions apply. Disputes regarding whether a breach is 'material' shall be resolved through binding arbitration."`,
  },

  recs: {
    id: 'recs',
    e2key: 'recs',
    tier: 'admin',
    weight: 1,
    title: 'RECs & Environmental Attributes',
    concept: `Renewable Energy Certificates (RECs) represent the environmental attributes of 1 MWh of renewable generation. In a VPPA, the buyer typically receives the RECs associated with the contracted generation — this is what gives the corporate buyer the right to claim 100% renewable electricity. REC quality matters: same-technology, same-region RECs (e.g., ERCOT Texas Solar RECs) are the gold standard for additionality claims; generic national RECs are lower quality. Unbundled RECs can be transferred separately from energy settlement.`,
    whyMatters: `For corporate sustainability reporting, the quality of RECs determines what claims the buyer can make. CDP, RE100, and the GHG Protocol have specific requirements. Delivering Texas Wind RECs to a California load is generally not considered location-matched and may not satisfy sophisticated sustainability frameworks. As corporate renewable claims face increasing scrutiny from investors and regulators, REC quality is increasingly important.`,
    scoring: [
      { label: 'RECs conveyed — same tech & region', score: '5', rationale: 'Highest quality. Exact technology and regional match. Satisfies all major sustainability frameworks including GHG Protocol location-based accounting.' },
      { label: 'RECs conveyed — same region any renewable', score: '15', rationale: 'Regional match but technology may differ. Satisfies most frameworks but limits additionality narrative.' },
      { label: 'RECs conveyed — any national REC', score: '35', rationale: 'Low quality. National RECs (e.g., from any U.S. state) have minimal additionality value. Not acceptable for sophisticated reporting.' },
      { label: 'Cash only — no RECs conveyed', score: '40', rationale: 'Buyer receives financial settlement but no renewable energy claim. Defeats the primary sustainability purpose of most VPPAs.' },
      { label: 'No RECs / not specified', score: '65–72', rationale: 'Critical gap. Buyer must separately source RECs to make renewable claims. Significantly reduces VPPA\'s sustainability value.' },
    ],
    watchFor: [
      'REC vintage requirements — RECs should be from the same year as generation',
      '"Any WECC REC" — wide region, low additionality',
      'Unbundled RECs that can be sold separately — buyer should ensure bundled delivery',
      'No WREGIS/ERCOT registry account access — buyer cannot retire RECs',
    ],
    favorable: `"Seller shall transfer to Buyer all Environmental Attributes associated with the Contract Quantity, including all RECs generated by the Project, certified under [ERCOT/WREGIS] and registered in Buyer's registry account within 30 days of generation."`,
    unfavorable: `"Seller retains all Environmental Attributes associated with the Project's generation. Buyer may purchase RECs from the market or any other source to meet its renewable energy obligations."`,
  },

  incentives: {
    id: 'incentives',
    e2key: 'incentives',
    tier: 'admin',
    weight: 1,
    title: 'Tax Credits & Incentives',
    concept: `The Investment Tax Credit (ITC) and Production Tax Credit (PTC) are federal tax incentives for renewable energy. In a VPPA, the developer typically retains these credits — they are a key component of project economics and financing. The question for the buyer: is the strike price transparently set to reflect the tax credit benefit, or is the developer double-dipping (keeping the ITC and also pricing the contract as if it weren't receiving a subsidy)?`,
    whyMatters: `The 30% ITC under the Inflation Reduction Act (2022) is worth $180–350M on a 200 MW solar project. This credit substantially reduces the developer's cost basis. If the developer retains the full ITC benefit but doesn't reflect it in the strike price (i.e., prices the contract as if there were no ITC), the buyer is overpaying by the equivalent of the ITC subsidy. Transparency about tax credit treatment is increasingly a negotiating point.`,
    scoring: [
      { label: 'Buyer shares ITC upside', score: '5', rationale: 'Developer shares ITC benefit with buyer through reduced strike. Most favorable. Increasingly common in competitive procurements.' },
      { label: 'Seller retains — strike reflects', score: '20', rationale: 'Developer retains ITC but the strike price transparently accounts for the subsidy. Fair and common. Buyer gets market-rate pricing.' },
      { label: 'Seller retains — no transparency', score: '50', rationale: 'Developer keeps ITC and pricing is opaque. Buyer cannot verify whether contract economics are fair. Potential overpricing risk.' },
      { label: 'Not specified', score: '55', rationale: 'Tax credit treatment undisclosed. Always request explicit disclosure of ITC retention and strike price derivation.' },
    ],
    watchFor: [
      'No ITC disclosure in term sheet — always ask explicitly',
      'IRA domestic content bonus credits (10%) not disclosed — additional upside for developer',
      'ITC transferability — developer may monetize credit through third-party transfer',
      'Change in law provisions that shift ITC reduction risk to buyer',
    ],
    favorable: `"The Strike Price has been calculated to reflect the benefit of the 30% Investment Tax Credit available under Section 48 of the Internal Revenue Code, as amended by the Inflation Reduction Act. Seller shall provide Buyer with a written explanation of ITC assumptions underlying the Strike Price."`,
    unfavorable: `"Seller shall retain all Tax Credits available in connection with the Project. Buyer shall have no interest in or claim to any Tax Credit. The Strike Price has been determined by Seller in its sole discretion."`,
  },

  govlaw: {
    id: 'govlaw',
    e2key: 'govlaw',
    tier: 'admin',
    weight: 1,
    title: 'Governing Law',
    concept: `Governing law specifies which state's laws interpret and govern the contract. For power contracts, New York and Delaware are preferred for their well-developed commercial law and predictable enforcement of sophisticated financial agreements. Texas is common for ERCOT projects. The governing law affects how disputes are interpreted, what implied terms apply, and how courts treat ambiguous provisions.`,
    whyMatters: `For a $100–500M long-term contract, governing law determines your rights if a dispute arises. New York law has deep precedent on energy contracts, financial instruments, and commercial obligations. Some developer-preferred states have less developed commercial law or more debtor-friendly bankruptcy provisions. Dispute resolution venue (arbitration vs. litigation, location) is equally important.`,
    scoring: [
      { label: 'New York', score: '5', rationale: 'Gold standard for commercial contracts. Deep precedent, sophisticated courts, predictable enforcement. Most buyer-favorable.' },
      { label: 'Delaware', score: '8', rationale: 'Strong commercial law. Entity law is excellent but energy contract precedent thinner than NY. Good choice.' },
      { label: 'Texas', score: '12', rationale: 'Appropriate for ERCOT projects. Texas courts have substantial energy contract experience. Acceptable.' },
      { label: 'Other state', score: '20', rationale: 'May have thinner precedent. Review dispute resolution provisions carefully. Not immediately disqualifying.' },
    ],
    watchFor: [
      'Governing law inconsistent with project state — may create conflict of laws issues',
      'Jury trial waiver absent — can lead to unpredictable jury outcomes in energy disputes',
      'Arbitration vs. litigation choice — arbitration faster but no appeal, litigation allows appeal',
      'Venue specified in developer\'s home jurisdiction — inconvenient for buyer',
    ],
    favorable: `"This Agreement shall be governed by and construed in accordance with the laws of the State of New York, without regard to its conflict of laws provisions. Each Party waives its right to a jury trial."`,
    unfavorable: `"This Agreement shall be governed by and construed in accordance with the laws of the State of [Developer's Home State]. All disputes shall be resolved through binding arbitration before a single arbitrator selected by Seller."`,
  },

  conf: {
    id: 'conf',
    e2key: 'conf',
    tier: 'admin',
    weight: 1,
    title: 'Confidentiality',
    concept: `Confidentiality provisions restrict what each party can disclose about the contract — its existence, pricing, terms, and the parties' identities. Scope ranges from narrow (pricing and financial terms only) to broad (existence of the agreement cannot be disclosed). For corporate buyers, overly broad confidentiality can conflict with SEC disclosure obligations, investor ESG reporting, and sustainability marketing.`,
    whyMatters: `Corporate buyers often want to publicize their renewable energy deals for sustainability marketing, investor relations, and brand value. A confidentiality provision that covers the existence of the agreement or prohibits naming the project/developer can prevent this entirely. Conversely, buyers may want pricing confidentiality to maintain competitive advantage. The balance between these interests is a common negotiation point.`,
    scoring: [
      { label: 'Narrow (pricing only)', score: '15', rationale: 'Only financial terms are confidential. Buyer can disclose project location, capacity, developer, and renewable energy claim. Maximum marketing flexibility.' },
      { label: 'Standard (all material terms)', score: '30', rationale: 'Financial and commercial terms confidential, but existence and general parameters can be disclosed. Industry standard.' },
      { label: 'Broad (existence included)', score: '55', rationale: 'Even the existence of the agreement is confidential. Conflicts with SEC disclosure obligations and sustainability reporting. Highly restrictive.' },
    ],
    watchFor: [
      'Confidentiality of existence conflicting with SEC 8-K material contract disclosure obligations',
      'No carve-out for required legal disclosures (regulatory filings, court orders)',
      'No ESG/sustainability reporting carve-out — prevents CDP, GRI, and RE100 reporting',
      'Indefinite confidentiality duration — should expire 2–3 years post-termination',
    ],
    favorable: `"The financial terms of this Agreement are Confidential Information. Neither Party shall disclose the Strike Price or Settlement Amounts without prior written consent. Buyer may disclose the existence of this Agreement, the Project name, contracted capacity, and its renewable energy claim for ESG, sustainability, and investor reporting purposes."`,
    unfavorable: `"The existence, terms, and all information relating to this Agreement are Confidential Information. Neither Party may disclose any aspect of this Agreement to any third party without the prior written consent of the other Party."`,
  },

  excl: {
    id: 'excl',
    e2key: 'excl',
    tier: 'admin',
    weight: 1,
    title: 'Exclusivity',
    concept: `Exclusivity provisions govern whether the developer is obligated to dedicate the project's entire output to this buyer, or whether they can sell portions to other buyers. A fully committed project means all energy is under this contract. A partially committed project means the developer has optionality to sell remaining output in the merchant market or to other offtakers — which can affect dispatch decisions and settlement.`,
    whyMatters: `If a developer has a 300 MW project but only commits 150 MW to this buyer, the developer retains economic optionality on the remaining 150 MW. This can affect scheduling and dispatch decisions in ways that may not align with the buyer's interests. A non-exclusive developer may choose to sell peak-hour generation in the merchant market rather than into the VPPA settlement, reducing the buyer's effective hedge.`,
    scoring: [
      { label: 'Full project committed', score: '10', rationale: 'Entire project output is dedicated to this buyer. Developer has no competing economic interests. Alignment of incentives.' },
      { label: 'Partial project', score: '40', rationale: 'Developer retains portion of project for other uses. Potential for conflicting dispatch incentives.' },
      { label: 'Not specified', score: '55', rationale: 'Exclusivity not addressed. Developer may have partial commitment that is undisclosed.' },
    ],
    watchFor: [
      'Partial project structure with developer retaining highest-value generation periods',
      'No merchant exposure disclosure — how much of project is unsold?',
      'Exclusivity limited to "contracted capacity" which may be defined narrowly',
    ],
    favorable: `"Seller hereby dedicates 100% of the Project's net generation capacity to this Agreement. Seller shall not enter into any other offtake agreement or merchant sale that would impair Seller's obligations hereunder."`,
    unfavorable: `"Buyer shall be entitled to the economic benefit of [X] MW of the Project's generating capacity. Seller retains full rights to sell any remaining generation, capacity, or attributes to any third party without notice to Buyer."`,
  },

  expenses: {
    id: 'expenses',
    e2key: 'expenses',
    tier: 'admin',
    weight: 1,
    title: 'Expenses & Fees',
    concept: `Expense provisions allocate legal, administrative, and transactional costs — who pays for the contract drafting and negotiation (legal fees), ongoing administrative costs (meter reading, registry fees), regulatory fees, and implementation expenses. Standard practice is each-party-bears-own-legal-fees. Deviation from this (buyer bears developer's legal costs, shared costs without definition) is a negotiating point.`,
    whyMatters: `On a large complex VPPA, legal fees can reach $200–500K per side. Shared administrative costs can be $20–50K/year. While individually manageable, these provisions create budget exposure and can create conflict if not defined. Unexpected cost allocations (buyer unexpectedly bears regulatory filing costs) are a common source of post-signing disputes.`,
    scoring: [
      { label: 'Each party bears own', score: '20', rationale: 'Standard market practice. No exposure to counterparty\'s legal or advisory costs. Clean and predictable.' },
      { label: 'Shared', score: '30', rationale: 'Cost sharing acceptable if scope is clearly defined. Savings from shared resources can be real.' },
      { label: 'Buyer bears', score: '60', rationale: 'Buyer responsible for some or all joint costs. Creates open-ended expense exposure. Negotiate carefully.' },
    ],
    watchFor: [
      'Undefined "administrative costs" that buyer must share',
      'Regulatory filing costs allocated to buyer without cap',
      'Ongoing WREGIS/GATS registry fees not explicitly allocated',
      'Dispute resolution costs — who bears arbitration or litigation costs?',
    ],
    favorable: `"Each Party shall bear its own legal fees, advisory fees, and expenses in connection with the negotiation, execution, and administration of this Agreement."`,
    unfavorable: `"Buyer shall bear all reasonable costs and expenses incurred by Seller in connection with contract administration, including regulatory filings, registry maintenance, and any costs related to Buyer's requests for data or reporting."`,
  },

  acct: {
    id: 'acct',
    e2key: 'acct',
    tier: 'admin',
    weight: 1,
    title: 'Accounting Treatment',
    concept: `Accounting treatment provisions address how the VPPA is classified under US GAAP (or IFRS). The critical question: does the contract qualify as a derivative that must be marked-to-market on the balance sheet (creating quarterly P&L volatility), or can it receive hedge accounting treatment (smoothing P&L impact)? Hedge accounting requires designation, documentation, and effectiveness testing under ASC 815. Some contracts include representations about accounting structure.`,
    whyMatters: `VPPAs that fail to receive hedge accounting treatment create significant quarterly earnings volatility. As electricity prices move, the fair value of the VPPA changes — potentially by tens of millions of dollars per quarter. CFOs and audit committees are increasingly focused on this. Some companies prefer to own the accounting treatment decision; others want contractual representations from the developer that the structure supports hedge accounting.`,
    scoring: [
      { label: 'Both parties provide accounting reps', score: '15', rationale: 'Developer acknowledges structure is designed to support buyer\'s accounting treatment. Cooperative. Reduces risk of adverse accounting outcomes.' },
      { label: 'Buyer only provides accounting reps', score: '30', rationale: 'Buyer makes representations about its own accounting treatment — one-sided. Some protection for buyer but developer uncommitted.' },
      { label: 'None', score: '50', rationale: 'No accounting provisions. Buyer must independently assess and document hedge accounting qualification.' },
    ],
    watchFor: [
      'Contract structure that precludes hedge accounting (e.g., pricing basis not matching buyer\'s load)',
      'No settlement netting — may create mark-to-market requirements',
      'Change in accounting standards not addressed — new standards (ASC 842, etc.) could affect treatment',
      'Contract not structured as a financial instrument — limits accounting flexibility',
    ],
    favorable: `"The Parties intend this Agreement to qualify as a cash flow hedge under ASC 815. Each Party shall cooperate in executing any documentation necessary to achieve or maintain hedge accounting treatment, including ISDA Master Agreement schedules if required."`,
    unfavorable: `"Seller makes no representation regarding the accounting treatment of this Agreement by Buyer. Buyer is solely responsible for determining the appropriate accounting classification of this Agreement under applicable accounting standards."`,
  },

  publicity: {
    id: 'publicity',
    e2key: 'publicity',
    tier: 'admin',
    weight: 1,
    title: 'Publicity & Press',
    concept: `Publicity provisions govern press releases, marketing materials, case studies, and public announcements about the deal. Typically, both parties want to announce the signing — buyers for sustainability marketing, developers for project credibility and future deal flow. But the timing, content, and approval process matter. "Mutual approval" means neither side can publish without the other's consent.`,
    whyMatters: `For corporate buyers who have made public commitments to renewable energy targets, timely announcement of a PPA signing is often strategically important. A developer who can unilaterally announce the deal (including the buyer's name, deal size, and pricing) before the buyer's internal communications are ready creates reputational risk. Conversely, buyers who want to announce to investors before COD need developer cooperation.`,
    scoring: [
      { label: 'Mutual approval required', score: '15', rationale: 'Both parties must approve any public announcement. Maximum control. Good for buyers sensitive about timing and messaging.' },
      { label: 'Notification only', score: '35', rationale: 'Either party can publish with advance notice. Less control but workable for most situations.' },
      { label: 'No restriction', score: '55', rationale: 'Either party can publish anything. Buyer has no approval rights over developer\'s announcements.' },
    ],
    watchFor: [
      'Developer using buyer\'s name in marketing materials without specific consent',
      'No time limit for approval — developer can delay indefinitely',
      'Announcement containing pricing or deal economics — confidentiality conflict',
      'Logo usage rights granted to developer without approval process',
    ],
    favorable: `"Neither Party shall issue any press release, public announcement, or marketing material referencing this Agreement or the other Party without the prior written consent of the other Party, not to be unreasonably withheld or delayed."`,
    unfavorable: `"Seller may reference Buyer's name and this Agreement in any marketing materials, investor presentations, or press releases without Buyer's prior consent."`,
  },

  reputation: {
    id: 'reputation',
    e2key: 'reputation',
    tier: 'admin',
    weight: 1,
    title: 'Reputational Provisions',
    concept: `Reputational provisions (sometimes called "reputation termination rights" or "moral clause provisions") give one or both parties the right to terminate the agreement if the other party becomes publicly associated with conduct materially harmful to the terminating party's reputation. These are more common in large corporate deals where brand association risk is real. The standard question: does the buyer have a unilateral right to exit if the developer is involved in, say, a serious environmental violation, labor scandal, or criminal investigation?`,
    whyMatters: `A corporate buyer's ESG credibility can be damaged by association with a developer involved in environmental violations, worker safety incidents, or governance scandals. As institutional investors scrutinize supply chain ESG risk, a 20-year contract with a developer who subsequently faces serious reputational issues creates ongoing exposure. A buyer termination right (with limited or no termination payment) is the clearest protection.`,
    scoring: [
      { label: 'Buyer unilateral termination right', score: '10', rationale: 'Buyer can exit if developer engages in specified reputational events. Maximum protection. Important for ESG-sensitive buyers.' },
      { label: 'Mutual termination right', score: '25', rationale: 'Either party can exit for reputational cause. Balanced. Developer can also exit if buyer is implicated — relevant for high-profile corporate buyers.' },
      { label: 'No termination right', score: '55', rationale: 'Neither party has a reputational exit. Buyer is contractually bound regardless of developer\'s conduct. Increasing risk for ESG-focused organizations.' },
    ],
    watchFor: [
      'Reputational trigger defined subjectively — buyer discretion vs. objective threshold',
      'No distinction between reputational events and material breach (different remedies)',
      'Termination payment required for reputational exit — makes right illusory',
      'Definition of "reputational harm" so narrow it excludes most realistic scenarios',
    ],
    favorable: `"Buyer shall have the right to terminate this Agreement upon 30 days' written notice if Seller is publicly associated with conduct that, in Buyer's reasonable judgment, would materially damage Buyer's reputation, including any material violation of environmental laws, labor standards, or applicable anti-corruption laws."`,
    unfavorable: `"No Party shall have the right to terminate this Agreement based on reputational concerns. All terminations must be based on a specific contractual breach as defined herein."`,
  },

  product: {
    id: 'product',
    e2key: 'product',
    tier: 'admin',
    weight: 1,
    title: 'Product Definition',
    concept: `Product definition specifies exactly what the buyer is purchasing — the combination of energy and environmental attributes. A "bundled" product includes both energy settlement and RECs in a single transaction. An "unbundled" product separates energy settlement (the financial hedge component) from RECs (the environmental attribute). Whether all output is conveyed, or whether certain attributes (capacity payments, ancillary services) are carved out, determines the complete value stack the buyer receives.`,
    whyMatters: `The product definition determines whether you receive a complete, integrated renewable energy purchase or a partial bundle with retained developer revenue streams. In markets with capacity payments (PJM ICAP, ISO-NE NEPOOL) or active ancillary services markets, the value of retained attributes can be $3–8/MWh — material relative to a $45–65 strike. Understanding exactly what is and isn't included prevents post-signing disputes about revenue allocation.`,
    scoring: [
      { label: 'All output conveyed — bundled', score: '5', rationale: 'Complete product. Buyer receives energy settlement, RECs, and all ancillary revenues. Maximum value. No retained developer revenue.' },
      { label: 'All output conveyed — unbundled', score: '20', rationale: 'Energy and RECs separated. Buyer receives both but as separate instruments. Slightly more administrative complexity.' },
      { label: 'Partial carveouts', score: '35–50', rationale: 'Developer retains some revenue streams (capacity, ancillary). Buyer receives reduced value stack. Evaluate quantitatively.' },
      { label: 'Not defined', score: '60', rationale: 'Product ambiguity. Disputes likely about what is included. Must be resolved before execution.' },
    ],
    watchFor: [
      'Capacity market revenues retained by developer — material in PJM ($5–15/MWh equivalent)',
      'Ancillary services carved out without quantitative disclosure of historical revenues',
      'RECs conveyed separately from energy — ensure they are actually transferred',
      '"All-in" language that does not explicitly list what is included',
    ],
    favorable: `"The Product includes all net generation from the Project, all associated Environmental Attributes (including RECs), all capacity market revenues, and all ancillary service revenues attributable to the Contract Quantity. No revenues or attributes are retained by Seller."`,
    unfavorable: `"The Product is energy only. Seller retains all Environmental Attributes, Capacity Market revenues, Ancillary Service revenues, and any other attributes or revenues associated with the Project's generation."`,
  },

};

// Export
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { KB };
} else {
  window.KB = KB;
}
